version: '3.8'

services:
  # backend:
  #   build: .
  #   container_name: assistant-ui-backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app  # Mount current directory for hot reload
  #     - ./tools:/app/tools  # Ensure tools directory is mounted
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   env_file:
  #     - .env
  #   command: uvicorn main_structured:app --host 0.0.0.0 --port 8000 --reload

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: assistant-ui-mcp-server
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8001
    env_file:
      - .env
